---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  # Debian
  - name: bookworm
    image: geerlingguy/docker-debian12-ansible:latest
    pre_build_image: true
  - name: trixie
    image: geerlingguy/docker-debian13-ansible:latest
    pre_build_image: true
  # Ubuntu
  - name: jammy
    image: geerlingguy/docker-ubuntu2204-ansible:latest
    pre_build_image: true
  - name: noble
    image: geerlingguy/docker-ubuntu2404-ansible:latest
    pre_build_image: true
provisioner:
  name: ansible
verifier:
  name: ansible
